require "../shared.rb"

Vagrant.configure("2") do |config|
	vm(config, "master", "fedora/26-cloud-base")
	vm(config, "slave", "fedora/26-cloud-base") do |ansible|
		ansible.groups = {
			"jenkins_master" => ["master"],
			"jenkins_slave" => ["slave"],
			"fedora" => ["master", "slave"],
			"repositories" => ["master"],
			"jenkins_slave:vars" => {
				"jenkins_master_url" => "http://{{ hostvars['master']['ansible_default_ipv4']['address'] }}"
			}
		}
	end
end
