require "../shared.rb"
require 'json'

base = File.dirname(__FILE__)

Vagrant.configure("2") do |config|
    vm(config, "master")
    vm(config, "slave") do |ansible|
        ansible.groups = {
            "jenkins_master" => ["master"],
            "jenkins_slave" => ["slave"],
            "cent7" => ["master", "slave"],
            "repositories" => ["master", "slave"],
            "jenkins_slave:vars" => {
                "jenkins_master_url" => "http://{{ hostvars['master']['ansible_default_ipv4']['address'] }}:8080",
                "jenkins_user_password" => "vagrant",
                "jenkins_user" => "jenkins",
                "jenkins_user_home" => "/var/lib/jenkins"
            },
            "jenkins_master:vars" => {
                "jenkins_ssl_cert" => "vagrant/master/jenkins.crt",
                "jenkins_ssl_key" => "vagrant/master/jenkins.key",
                "https_enabled" => "False"
            },
            "cent7:vars" => {
                # These variables need to be converted to JSON objects, like
                # all other copmlex value passed into the inventory file for
                # Ansible. We here utilize standard Ruby modules to
                # accomplish that
                "pre_upload_files" => [
                    {"src" => base + "/simple", "dest" => "/simple"},
                    {"src" => base + "/mode", "dest" => "/mode", "mode" => "0600"}
                ].to_json,
                "post_upload_files" => [
                    {"src" => base + "/owner", "dest" => "/var/lib/jenkins/owner", "owner" => "jenkins"}
                ].to_json
            }
        }
    end
end
