require "../shared.rb"

Vagrant.configure("2") do |config|
    vm(config, "master")
    vm(config, "slave", "centos/6") do |ansible|
        ansible.groups = {
            "jenkins_master" => ["master"],
            "jenkins_slave" => ["slave"],
            "cent7" => ["master"],
            "cent6" => ["slave"],
            "repositories" => ["master", "slave"],
            "jenkins_slave:vars" => {
                "jenkins_master_url" => "http://{{ hostvars['master']['ansible_default_ipv4']['address'] }}",
                "jenkins_user_password" => "vagrant",
                "jenkins_user" => "jenkins",
                "jenkins_user_home" => "/var/lib/jenkins"
            },
            "jenkins_master:vars" => {
                "https_enabled" => "False"
            }
        }
    end
end
