require "../shared.rb"

Vagrant.configure("2") do |config|
    vm(config, "master") do |ansible|
        ansible.groups = {
            "jenkins_master" => ["master"],
            "cent7" => ["master"],
            "repositories" => ["master"]
        }
    end
end
