require "../shared.rb"

Vagrant.configure("2") do |config|
    vm(config, "master", "rhel7.2") do |ansible|
         ansible.groups = {
            "jenkins_master" => ["master"],
            "rhel7" => ["master"],
            "repositories" => ["master"],
            "jenkins_master:vars" => {
                "rhel_base" => "http://example.com/content/dist/rhel/server/7/7.2"
            }
        }
    end
end
