require "../shared.rb"

Vagrant.configure("2") do |config|
    vm(config, "master", "samdoran/rhel7") do |ansible|
         ansible.groups = {
            "jenkins_master" => ["master"],
            "rhel7" => ["master"],
            "repositories" => ["master"],
            "jenkins_master:vars" => {
                "jenkins_ssl_cert" => "vagrant/master/jenkins.crt",
                "jenkins_ssl_key" => "vagrant/master/jenkins.key",
                "rhel_base" => "http://example.com/content/dist/rhel/server/7/7.2"
            }
        }
    end
end
