require "../shared.rb"

Vagrant.configure("2") do |config|
	vm(config, "master") do |ansible|
		ansible.groups = {
			"jenkins_master" => ["master"],
			"cent7" => ["master"],
			"repositories" => ["master"],
			"jenkins_master:vars" => {
				"jenkins_cli_shell_user" => "derpuser",
				"jenkins_cli_shell_user_home" => "/home/derpuser"
			}
		}
	end
end
